import 'package:flutter/material.dart';

class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;

  static const supportedLocales = [Locale('en'), Locale('ar')];

  static const _localizedValues = {
    'en': {
      'app_title': 'ConnecQ Productivity OS',
      'skip': 'Skip',
      'next': 'Next',
      'get_started': 'Get Started',
      'login': 'Login',
      'login_guest': 'Login as guest',
      'email': 'Email address',
      'password': 'Password',
      'forgot_password': 'Forgot password?',
      'register': 'Register',
      'dashboard': 'Dashboard',
      'projects': 'Projects',
      'tasks': 'Tasks',
      'calendar': 'Calendar',
      'calendar_overview': 'Monthly overview',
      'calendar_selected_day': 'Tasks for {date}',
      'calendar_empty': 'No tasks scheduled for this day.',
      'calendar_previous_month': 'Previous month',
      'calendar_next_month': 'Next month',
      'finance': 'Finance Overview',
      'tools': 'Tools',
      'catalog': 'Catalog',
      'compare': 'Compare',
      'search': 'Search',
      'notifications': 'Notifications',
      'notifications_empty': 'You are all caught up for now!',
      'project_linked_tasks': 'Linked tasks',
      'project_progress': 'Progress {percent}%',
      'mark_completed': 'Mark as completed',
      'mark_active': 'Mark as active',
      'add_to_compare': 'Add to compare',
      'remove_from_compare': 'Remove from compare',
      'project_no_tasks': 'No related tasks yet.',
      'settings': 'Settings',
      'theme': 'Theme',
      'language': 'Language',
      'dark_mode': 'Dark Mode',
      'primary_color': 'Primary color',
      'ai_placeholder': 'AI assistant will be available in a future version.',
      'done': 'Done',
      'refreshing': 'Refreshing data...',
      'good_morning': 'Good morning, {name}',
      'onboarding_title_1': 'Organize your work beautifully',
      'onboarding_desc_1': 'Stay in control of projects, tasks and resources in a single flow.',
      'onboarding_title_2': 'Collaborate in pastel calm',
      'onboarding_desc_2': 'Share progress with your team in a soft, minimal dashboard.',
      'onboarding_title_3': 'Plan smarter with ConnecQ',
      'onboarding_desc_3': 'Track time, finances and catalog assets without friction.',
      'projects_subtitle': 'Your running initiatives',
      'search_projects_hint': 'Search projects',
      'filter_all': 'All',
      'priority_high': 'High',
      'priority_medium': 'Medium',
      'priority_low': 'Low',
      'compare_selected': 'Compare ({count})',
      'compare_header': 'Compare items',
      'compare_empty': 'Select up to three items to compare them side by side.',
      'clear_compare': 'Clear comparison list',
      'compare_type': 'Type',
      'compare_priority': 'Priority',
      'compare_status': 'Status',
      'compare_estimate': 'Estimated time',
      'compare_due': 'Due date',
      'payment_summary': 'Payment summary',
      'payment_invoices': 'Invoices',
      'payment_subscriptions': 'Subscriptions',
      'monthly_tasks': 'Monthly tasks',
      'dashboard_high_priority': 'High priority projects',
      'dashboard_today_tasks': 'Today tasks',
      'dashboard_focus_hours': 'Focus hours',
      'tasks_today': 'Today',
      'tasks_calendar': 'Calendar',
      'tasks_total': 'Total tasks',
      'tasks_average': 'Avg per day',
      'tasks_hours': 'Total hours',
      'search_tasks_hint': 'Search tasks',
      'task_details_schedule': 'Schedule',
      'task_due_date': 'Due {date}',
      'task_details_description': 'Description',
      'task_details_hours': 'Estimated hours',
      'task_details_mark_done': 'Mark as done',
      'task_details_mark_active': 'Mark as active',
      'task_details_marked_done': 'Task marked as done',
      'task_details_marked_active': 'Task set back to active',
      'task_overlay_front': 'Preview asset. Tap to flip for details.',
      'filter_status': 'Status',
      'status_in_progress': 'In progress',
      'status_upcoming': 'Upcoming',
      'status_done': 'Done',
      'load_more': 'Load more',
      'catalog_search_hint': 'Search catalog',
      'type_template': 'Template',
      'type_document': 'Document',
      'type_task': 'Task',
      'view_list': 'List',
      'view_grid': 'Grid',
      'compare_selected_full': 'Compare selected ({count})',
      'language_en': 'English',
      'language_ar': 'Arabic',
      'primary_color': 'Primary color',
      'dark_mode': 'Dark Mode',
      'profile_trial': 'Trial ends in {days} days',
      'invalid_email': 'Please enter a valid email',
      'required_field': 'This field is required',
      'password_too_short': 'Password must be at least 6 characters',
      'password_mismatch': 'Passwords do not match',
      'email_address': 'Email address',
      'full_name': 'Full name',
      'confirm_password': 'Confirm password',
      'password_strength': 'Password strength',
      'search_global_hint': 'Search anything',
      'search_results_projects': 'Projects',
      'search_results_tasks': 'Tasks',
      'search_results_catalog': 'Catalog',
      'search_results_templates': 'Templates',
      'drawer_trial': 'Trial',
      'settings_profile': 'Account details',
      'settings_subscription': 'Subscription plan',
      'settings_brand': 'Brand elements',
      'settings_bank': 'Bank account',
      'ai_future_title': 'Coming soon',
      'ai_future_message': 'AI assistant will be available in a future version.'
    },
    'ar': {
      'app_title': 'نظام كونيك كيو للإنتاجية',
      'skip': 'تخطي',
      'next': 'التالي',
      'get_started': 'ابدأ الآن',
      'login': 'تسجيل الدخول',
      'login_guest': 'الدخول كضيف',
      'email': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'forgot_password': 'هل نسيت كلمة المرور؟',
      'register': 'إنشاء حساب',
      'dashboard': 'لوحة التحكم',
      'projects': 'المشاريع',
      'tasks': 'المهام',
      'calendar': 'التقويم',
      'calendar_overview': 'نظرة شهرية',
      'calendar_selected_day': 'مهام يوم {date}',
      'calendar_empty': 'لا توجد مهام مجدولة لهذا اليوم.',
      'calendar_previous_month': 'الشهر السابق',
      'calendar_next_month': 'الشهر التالي',
      'finance': 'نظرة مالية',
      'tools': 'الأدوات',
      'catalog': 'كتالوج',
      'compare': 'مقارنة',
      'search': 'بحث',
      'notifications': 'الإشعارات',
      'notifications_empty': 'لا توجد إشعارات جديدة حالياً!',
      'project_linked_tasks': 'المهام المرتبطة',
      'project_progress': 'التقدم {percent}%',
      'mark_completed': 'وضع علامة كمكتمل',
      'mark_active': 'وضع علامة كنشط',
      'add_to_compare': 'إضافة إلى المقارنة',
      'remove_from_compare': 'إزالة من المقارنة',
      'project_no_tasks': 'لا توجد مهام مرتبطة بعد.',
      'settings': 'الإعدادات',
      'theme': 'السمة',
      'language': 'اللغة',
      'dark_mode': 'الوضع الداكن',
      'primary_color': 'اللون الأساسي',
      'ai_placeholder': 'سيتوفر مساعد الذكاء الاصطناعي في إصدار لاحق.',
      'done': 'تم',
      'refreshing': 'جاري تحديث البيانات...',
      'good_morning': 'صباح الخير، {name}',
      'onboarding_title_1': 'نظم عملك بجمال',
      'onboarding_desc_1': 'ابقَ مسيطراً على المشاريع والمهام والموارد في تدفق واحد.',
      'onboarding_title_2': 'تعاون في أجواء هادئة',
      'onboarding_desc_2': 'شارك تقدمك مع الفريق في لوحة ناعمة وبسيطة.',
      'onboarding_title_3': 'خطط بذكاء مع كونيك كيو',
      'onboarding_desc_3': 'تتبع الوقت والمالية والكتالوج بدون عناء.',
      'projects_subtitle': 'مبادراتك الحالية',
      'search_projects_hint': 'بحث في المشاريع',
      'filter_all': 'الكل',
      'priority_high': 'عالي',
      'priority_medium': 'متوسط',
      'priority_low': 'منخفض',
      'compare_selected': 'مقارنة ({count})',
      'compare_header': 'مقارنة العناصر',
      'compare_empty': 'اختر حتى ثلاثة عناصر للمقارنة بينها.',
      'clear_compare': 'مسح قائمة المقارنة',
      'compare_type': 'النوع',
      'compare_priority': 'الأولوية',
      'compare_status': 'الحالة',
      'compare_estimate': 'الوقت التقديري',
      'compare_due': 'تاريخ الاستحقاق',
      'payment_summary': 'ملخص المدفوعات',
      'payment_invoices': 'الفواتير',
      'payment_subscriptions': 'الاشتراكات',
      'monthly_tasks': 'مهام الشهر',
      'dashboard_high_priority': 'المشاريع عالية الأولوية',
      'dashboard_today_tasks': 'مهام اليوم',
      'dashboard_focus_hours': 'ساعات التركيز',
      'tasks_today': 'اليوم',
      'tasks_calendar': 'التقويم',
      'tasks_total': 'إجمالي المهام',
      'tasks_average': 'متوسط يومي',
      'tasks_hours': 'إجمالي الساعات',
      'search_tasks_hint': 'بحث في المهام',
      'task_details_schedule': 'الجدول',
      'task_due_date': 'تاريخ الاستحقاق {date}',
      'task_details_description': 'الوصف',
      'task_details_hours': 'الساعات المقدرة',
      'task_details_mark_done': 'وضع علامة كمكتمل',
      'task_details_mark_active': 'وضع علامة كنشط',
      'task_details_marked_done': 'تم وضع علامة على المهمة كمكتملة',
      'task_details_marked_active': 'تمت إعادة المهمة كفعّالة',
      'task_overlay_front': 'معاينة للمهمة، اضغط للانقلاب ورؤية التفاصيل.',
      'filter_status': 'الحالة',
      'status_in_progress': 'قيد التنفيذ',
      'status_upcoming': 'قادمة',
      'status_done': 'منتهية',
      'load_more': 'تحميل المزيد',
      'catalog_search_hint': 'بحث في الكتالوج',
      'type_template': 'قالب',
      'type_document': 'مستند',
      'type_task': 'مهمة',
      'view_list': 'قائمة',
      'view_grid': 'شبكة',
      'compare_selected_full': 'مقارنة العناصر المختارة ({count})',
      'language_en': 'الإنجليزية',
      'language_ar': 'العربية',
      'primary_color': 'اللون الأساسي',
      'dark_mode': 'الوضع الداكن',
      'profile_trial': 'تنتهي الفترة التجريبية بعد {days} يومًا',
      'invalid_email': 'يرجى إدخال بريد إلكتروني صحيح',
      'required_field': 'هذا الحقل مطلوب',
      'password_too_short': 'يجب أن لا تقل كلمة المرور عن 6 أحرف',
      'password_mismatch': 'كلمتا المرور غير متطابقتين',
      'email_address': 'البريد الإلكتروني',
      'full_name': 'الاسم الكامل',
      'confirm_password': 'تأكيد كلمة المرور',
      'password_strength': 'قوة كلمة المرور',
      'search_global_hint': 'ابحث عن أي شيء',
      'search_results_projects': 'المشاريع',
      'search_results_tasks': 'المهام',
      'search_results_catalog': 'الكتالوج',
      'search_results_templates': 'القوالب',
      'drawer_trial': 'تجريبي',
      'settings_profile': 'تفاصيل الحساب',
      'settings_subscription': 'خطة الاشتراك',
      'settings_brand': 'عناصر الهوية',
      'settings_bank': 'الحساب البنكي',
      'ai_future_title': 'قريباً',
      'ai_future_message': 'سيتوفر مساعد الذكاء الاصطناعي في إصدار لاحق.'
    }
  };

  String translate(String key, {Map<String, String>? params}) {
    var value = _localizedValues[locale.languageCode]?[key] ?? key;
    if (params != null) {
      params.forEach((placeholder, replacement) {
        value = value.replaceAll('{$placeholder}', replacement);
      });
    }
    return value;
  }

  TextDirection get textDirection => locale.languageCode == 'ar' ? TextDirection.rtl : TextDirection.ltr;

  static AppLocalizations of(BuildContext context) => Localizations.of<AppLocalizations>(context, AppLocalizations)!;
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => AppLocalizations.supportedLocales.any((l) => l.languageCode == locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async => AppLocalizations(locale);

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}
