import 'package:flutter/material.dart';

class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;

  static const supportedLocales = [Locale('en'), Locale('ar')];

  static const _localizedValues = {
    'en': {
      'app_title': 'ConnecQ Productivity OS',
      'skip': 'Skip',
      'next': 'Next',
      'get_started': 'Get Started',
      'login': 'Login',
      'login_guest': 'Login as guest',
      'email': 'Email address',
      'password': 'Password',
      'forgot_password': 'Forgot password?',
      'register': 'Register',
      'dashboard': 'Dashboard',
      'projects': 'Projects',
      'tasks': 'Tasks',
      'calendar': 'Calendar',
      'calendar_overview': 'Monthly overview',
      'calendar_selected_day': 'Tasks for {date}',
      'calendar_empty': 'No tasks scheduled for this day.',
      'calendar_previous_month': 'Previous month',
      'calendar_next_month': 'Next month',
      'finance': 'Finance Overview',
      'finance_overview_subtitle': 'Track revenue, expenses, and invoices at a glance',
      'finance_tab_monthly': 'Monthly',
      'finance_tab_yearly': 'Yearly',
      'finance_summary_revenue': 'Revenue',
      'finance_summary_expenses': 'Expenses',
      'finance_summary_outstanding': 'Outstanding',
      'finance_summary_net': 'Net income',
      'finance_highlight_monthly': 'Strongest performing month',
      'finance_highlight_yearly': 'Top performing year',
      'finance_highlight_trend': '{percent}% vs previous period',
      'finance_progress_to_goal': 'to goal',
      'finance_chart_monthly': 'Revenue by month',
      'finance_chart_yearly': 'Revenue by year',
      'finance_bar_revenue': 'Revenue',
      'finance_bar_expenses': 'Expenses',
      'finance_invoices_section': 'Invoices spotlight',
      'finance_invoices_upcoming': 'Upcoming invoices',
      'finance_invoices_overdue': 'Overdue invoices',
      'finance_invoices_empty': 'No invoices to show right now.',
      'finance_invoices_all': 'All invoices',
      'finance_invoices_filter_label': 'Filter invoices',
      'finance_filter_all': 'All',
      'finance_filter_due': 'Due',
      'finance_filter_overdue': 'Overdue',
      'finance_filter_paid': 'Paid',
      'finance_invoice_status_due': 'Due',
      'finance_invoice_status_overdue': 'Overdue',
      'finance_invoice_status_paid': 'Paid',
      'finance_invoice_due_date': 'Due {date}',
      'finance_invoice_overdue_date': 'Overdue since {date}',
      'finance_invoice_paid_date': 'Paid on {date}',
      'finance_invoice_mark_paid': 'Mark as paid',
      'finance_load_more_invoices': 'Load more invoices',
      'finance_dashboard_outstanding': 'Outstanding: \${amount}',
      'tools': 'Tools',
      'tools_subtitle': 'Quick access to productivity spaces',
      'tools_calendar': 'Calendar planner',
      'tools_calendar_subtitle': 'Plan your month with highlights',
      'tools_scheduler': 'Scheduler',
      'tools_scheduler_empty': 'No events scheduled today',
      'tools_templates': 'Templates',
      'tools_templates_count': '{count} templates curated',
      'tools_library': 'Library',
      'tools_library_count': '{count} knowledge items',
      'tools_time_tracker': 'Time tracker',
      'tools_time_tracker_subtitle': '{last} last focus · {week} this week',
      'tools_tasks': 'All tasks',
      'tools_tasks_subtitle': 'Jump to your task board',
      'tools_spotlight_templates': 'Spotlight templates',
      'tools_recent_library': 'Recently updated library',
      'catalog': 'Catalog',
      'compare': 'Compare',
      'search': 'Search',
      'notifications': 'Notifications',
      'notifications_with_count': 'Notifications ({count})',
      'notifications_empty': 'You are all caught up for now!',
      'notifications_mark_all_read': 'Mark all read',
      'notifications_clear_all': 'Clear all',
      'notifications_section_pinned': 'Pinned',
      'notifications_section_recent': 'Recent updates',
      'notifications_mark_read': 'Mark as read',
      'notifications_mark_unread': 'Mark as unread',
      'notifications_pin': 'Pin to top',
      'notifications_unpin': 'Unpin',
      'project_linked_tasks': 'Linked tasks',
      'project_progress': 'Progress {percent}%',
      'mark_completed': 'Mark as completed',
      'mark_active': 'Mark as active',
      'add_to_compare': 'Add to compare',
      'remove_from_compare': 'Remove from compare',
      'project_no_tasks': 'No related tasks yet.',
      'settings': 'Settings',
      'theme': 'Theme',
      'language': 'Language',
      'dark_mode': 'Dark Mode',
      'primary_color': 'Primary color',
      'ai_placeholder': 'AI assistant will be available in a future version.',
      'done': 'Done',
      'refreshing': 'Refreshing data...',
      'good_morning': 'Good morning, {name}',
      'onboarding_title_1': 'Organize your work beautifully',
      'onboarding_desc_1': 'Stay in control of projects, tasks and resources in a single flow.',
      'onboarding_title_2': 'Collaborate in pastel calm',
      'onboarding_desc_2': 'Share progress with your team in a soft, minimal dashboard.',
      'onboarding_title_3': 'Plan smarter with ConnecQ',
      'onboarding_desc_3': 'Track time, finances and catalog assets without friction.',
      'projects_subtitle': 'Your running initiatives',
      'search_projects_hint': 'Search projects',
      'filter_all': 'All',
      'priority_high': 'High',
      'priority_medium': 'Medium',
      'priority_low': 'Low',
      'compare_selected': 'Compare ({count})',
      'compare_header': 'Compare items',
      'compare_empty': 'Select up to three items to compare them side by side.',
      'clear_compare': 'Clear comparison list',
      'compare_type': 'Type',
      'compare_priority': 'Priority',
      'compare_status': 'Status',
      'compare_estimate': 'Estimated time',
      'compare_due': 'Due date',
      'payment_summary': 'Payment summary',
      'payment_invoices': 'Invoices',
      'payment_subscriptions': 'Subscriptions',
      'monthly_tasks': 'Monthly tasks',
      'dashboard_high_priority': 'High priority projects',
      'dashboard_today_tasks': 'Today tasks',
      'dashboard_focus_hours': 'Focus hours',
      'dashboard_focus_title': 'Focus insights',
      'dashboard_focus_week_label': 'This week',
      'dashboard_focus_total_label': 'All time',
      'dashboard_focus_top_task': 'Top task · {task}',
      'dashboard_focus_top_task_empty': 'Track a session to reveal your top task.',
      'dashboard_focus_last': 'Last focus {duration} · {time}',
      'dashboard_focus_last_empty': 'No focus sessions logged yet.',
      'tasks_today': 'Today',
      'tasks_calendar': 'Calendar',
      'tasks_total': 'Total tasks',
      'tasks_average': 'Avg per day',
      'tasks_hours': 'Total hours',
      'search_tasks_hint': 'Search tasks',
      'scheduler_title': 'Scheduler',
      'scheduler_subtitle': 'Layer your day with themed sessions.',
      'scheduler_add_block': 'Add block',
      'scheduler_new_block': 'New schedule block',
      'scheduler_title_field': 'Title',
      'scheduler_description_field': 'Description',
      'scheduler_pick_time': 'Pick start time',
      'scheduler_duration_option': '{minutes} minutes',
      'scheduler_save': 'Save block',
      'scheduler_validation_title': 'Give the block a title first.',
      'scheduler_created_success': 'Schedule block added to your day.',
      'scheduler_empty': 'No sessions planned. Add your next focus block.',
      'scheduler_removed': 'Schedule block removed.',
      'scheduler_tag_focus': 'Focus',
      'scheduler_tag_team': 'Team',
      'scheduler_tag_client': 'Client',
      'scheduler_tag_deep_work': 'Deep work',
      'task_details_schedule': 'Schedule',
      'task_due_date': 'Due {date}',
      'task_details_description': 'Description',
      'task_details_hours': 'Estimated hours',
      'task_details_mark_done': 'Mark as done',
      'task_details_mark_active': 'Mark as active',
      'task_details_marked_done': 'Task marked as done',
      'task_details_marked_active': 'Task set back to active',
      'task_overlay_front': 'Preview asset. Tap to flip for details.',
      'filter_status': 'Status',
      'status_in_progress': 'In progress',
      'status_upcoming': 'Upcoming',
      'status_done': 'Done',
      'load_more': 'Load more',
      'catalog_search_hint': 'Search catalog',
      'type_template': 'Template',
      'type_document': 'Document',
      'type_task': 'Task',
      'view_list': 'List',
      'view_grid': 'Grid',
      'compare_selected_full': 'Compare selected ({count})',
      'language_en': 'English',
      'language_ar': 'Arabic',
      'primary_color': 'Primary color',
      'templates_title': 'Templates',
      'templates_subtitle': 'Save time with curated building blocks.',
      'templates_search_hint': 'Search templates',
      'templates_hours': '{hours}h estimate',
      'templates_added_to_catalog': 'Template added to your catalog.',
      'templates_add_to_catalog': 'Add to catalog',
      'templates_popular': 'Popular',
      'library_title': 'My Library',
      'library_subtitle': 'Documents, decks, and notes at a glance.',
      'library_search_hint': 'Search library',
      'library_link_copied': 'Link copied for quick sharing.',
      'time_tracker_title': 'Time tracker',
      'time_tracker_subtitle': 'Capture deep work sessions in pastel focus.',
      'time_tracker_task_label': 'Linked task',
      'time_tracker_no_task': 'Unassigned session',
      'time_tracker_last_session': 'Last session',
      'time_tracker_last_session_time': 'Logged {time}',
      'time_tracker_last_session_empty': 'No sessions logged yet.',
      'time_tracker_reset': 'Reset',
      'time_tracker_start': 'Start',
      'time_tracker_pause': 'Pause',
      'time_tracker_stop': 'Stop',
      'time_tracker_logged': 'Session logged successfully.',
      'time_tracker_summary_title': 'Focus summary',
      'time_tracker_weekly_total': '{duration} tracked this week',
      'time_tracker_total': '{duration} logged overall',
      'time_tracker_top_task': 'Most focused · {task}',
      'time_tracker_top_task_empty': 'Log a session to surface your top task.',
      'time_tracker_history': 'Session history',
      'time_tracker_history_empty': 'No focus sessions yet. Start one to build momentum.',
      'time_tracker_clear_history': 'Clear history',
      'time_tracker_session_at': 'Logged {time}',
      'time_tracker_history_cleared': 'Session history cleared.',
      'dark_mode': 'Dark Mode',
      'profile_trial': 'Trial ends in {days} days',
      'invalid_email': 'Please enter a valid email',
      'required_field': 'This field is required',
      'password_too_short': 'Password must be at least 6 characters',
      'password_mismatch': 'Passwords do not match',
      'email_address': 'Email address',
      'full_name': 'Full name',
      'confirm_password': 'Confirm password',
      'password_strength': 'Password strength',
      'search_global_hint': 'Search anything',
      'search_results_projects': 'Projects',
      'search_results_tasks': 'Tasks',
      'search_results_catalog': 'Catalog',
      'search_results_templates': 'Templates',
      'drawer_trial': 'Trial',
      'settings_profile': 'Account details',
      'settings_subscription': 'Subscription plan',
      'settings_brand': 'Brand elements',
      'settings_bank': 'Bank account',
      'ai_future_title': 'Coming soon',
      'ai_future_message': 'AI assistant will be available in a future version.'
    },
    'ar': {
      'app_title': 'نظام كونيك كيو للإنتاجية',
      'skip': 'تخطي',
      'next': 'التالي',
      'get_started': 'ابدأ الآن',
      'login': 'تسجيل الدخول',
      'login_guest': 'الدخول كضيف',
      'email': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'forgot_password': 'هل نسيت كلمة المرور؟',
      'register': 'إنشاء حساب',
      'dashboard': 'لوحة التحكم',
      'projects': 'المشاريع',
      'tasks': 'المهام',
      'calendar': 'التقويم',
      'calendar_overview': 'نظرة شهرية',
      'calendar_selected_day': 'مهام يوم {date}',
      'calendar_empty': 'لا توجد مهام مجدولة لهذا اليوم.',
      'calendar_previous_month': 'الشهر السابق',
      'calendar_next_month': 'الشهر التالي',
      'finance': 'نظرة مالية',
      'finance_overview_subtitle': 'تابع الإيرادات والمصروفات والفواتير في لمحة',
      'finance_tab_monthly': 'شهري',
      'finance_tab_yearly': 'سنوي',
      'finance_summary_revenue': 'الإيرادات',
      'finance_summary_expenses': 'المصروفات',
      'finance_summary_outstanding': 'المستحقات',
      'finance_summary_net': 'صافي الدخل',
      'finance_highlight_monthly': 'أفضل شهر أداءً',
      'finance_highlight_yearly': 'أفضل سنة أداءً',
      'finance_highlight_trend': '{percent}% مقارنة بالفترة السابقة',
      'finance_progress_to_goal': 'إلى الهدف',
      'finance_chart_monthly': 'الإيرادات حسب الشهر',
      'finance_chart_yearly': 'الإيرادات حسب السنة',
      'finance_bar_revenue': 'الإيرادات',
      'finance_bar_expenses': 'المصروفات',
      'finance_invoices_section': 'أضواء على الفواتير',
      'finance_invoices_upcoming': 'الفواتير القادمة',
      'finance_invoices_overdue': 'الفواتير المتأخرة',
      'finance_invoices_empty': 'لا توجد فواتير للعرض الآن.',
      'finance_invoices_all': 'جميع الفواتير',
      'finance_invoices_filter_label': 'تصفية الفواتير',
      'finance_filter_all': 'الكل',
      'finance_filter_due': 'مستحقة',
      'finance_filter_overdue': 'متأخرة',
      'finance_filter_paid': 'مدفوعة',
      'finance_invoice_status_due': 'مستحقة',
      'finance_invoice_status_overdue': 'متأخرة',
      'finance_invoice_status_paid': 'مدفوعة',
      'finance_invoice_due_date': 'تستحق في {date}',
      'finance_invoice_overdue_date': 'متأخرة منذ {date}',
      'finance_invoice_paid_date': 'دُفعت في {date}',
      'finance_invoice_mark_paid': 'تمييز كمدفوعة',
      'finance_load_more_invoices': 'تحميل المزيد من الفواتير',
      'finance_dashboard_outstanding': 'المستحقات: \${amount}',
      'tools': 'الأدوات',
      'tools_subtitle': 'وصول سريع لمساحات الإنتاجية',
      'tools_calendar': 'مخطط التقويم',
      'tools_calendar_subtitle': 'خطط شهرك مع النقاط المضيئة',
      'tools_scheduler': 'جدول المواعيد',
      'tools_scheduler_empty': 'لا توجد جلسات مجدولة اليوم',
      'tools_templates': 'القوالب',
      'tools_templates_count': '{count} قالب منسق',
      'tools_library': 'المكتبة',
      'tools_library_count': '{count} عنصر معرفي',
      'tools_time_tracker': 'متعقب الوقت',
      'tools_time_tracker_subtitle': '{last} في آخر جلسة · {week} هذا الأسبوع',
      'tools_tasks': 'جميع المهام',
      'tools_tasks_subtitle': 'انتقل مباشرة إلى لوحة المهام',
      'tools_spotlight_templates': 'قوالب مميزة',
      'tools_recent_library': 'مكتبة محدثة مؤخراً',
      'catalog': 'كتالوج',
      'compare': 'مقارنة',
      'search': 'بحث',
      'notifications': 'الإشعارات',
      'notifications_with_count': 'الإشعارات ({count})',
      'notifications_empty': 'لا توجد إشعارات جديدة حالياً!',
      'notifications_mark_all_read': 'تحديد الكل كمقروء',
      'notifications_clear_all': 'مسح جميع الإشعارات',
      'notifications_section_pinned': 'مثبتة',
      'notifications_section_recent': 'أحدث التحديثات',
      'notifications_mark_read': 'تحديد كمقروء',
      'notifications_mark_unread': 'تحديد كغير مقروء',
      'notifications_pin': 'تثبيت في الأعلى',
      'notifications_unpin': 'إلغاء التثبيت',
      'project_linked_tasks': 'المهام المرتبطة',
      'project_progress': 'التقدم {percent}%',
      'mark_completed': 'وضع علامة كمكتمل',
      'mark_active': 'وضع علامة كنشط',
      'add_to_compare': 'إضافة إلى المقارنة',
      'remove_from_compare': 'إزالة من المقارنة',
      'project_no_tasks': 'لا توجد مهام مرتبطة بعد.',
      'settings': 'الإعدادات',
      'theme': 'السمة',
      'language': 'اللغة',
      'dark_mode': 'الوضع الداكن',
      'primary_color': 'اللون الأساسي',
      'ai_placeholder': 'سيتوفر مساعد الذكاء الاصطناعي في إصدار لاحق.',
      'done': 'تم',
      'refreshing': 'جاري تحديث البيانات...',
      'good_morning': 'صباح الخير، {name}',
      'onboarding_title_1': 'نظم عملك بجمال',
      'onboarding_desc_1': 'ابقَ مسيطراً على المشاريع والمهام والموارد في تدفق واحد.',
      'onboarding_title_2': 'تعاون في أجواء هادئة',
      'onboarding_desc_2': 'شارك تقدمك مع الفريق في لوحة ناعمة وبسيطة.',
      'onboarding_title_3': 'خطط بذكاء مع كونيك كيو',
      'onboarding_desc_3': 'تتبع الوقت والمالية والكتالوج بدون عناء.',
      'projects_subtitle': 'مبادراتك الحالية',
      'search_projects_hint': 'بحث في المشاريع',
      'filter_all': 'الكل',
      'priority_high': 'عالي',
      'priority_medium': 'متوسط',
      'priority_low': 'منخفض',
      'compare_selected': 'مقارنة ({count})',
      'compare_header': 'مقارنة العناصر',
      'compare_empty': 'اختر حتى ثلاثة عناصر للمقارنة بينها.',
      'clear_compare': 'مسح قائمة المقارنة',
      'compare_type': 'النوع',
      'compare_priority': 'الأولوية',
      'compare_status': 'الحالة',
      'compare_estimate': 'الوقت التقديري',
      'compare_due': 'تاريخ الاستحقاق',
      'payment_summary': 'ملخص المدفوعات',
      'payment_invoices': 'الفواتير',
      'payment_subscriptions': 'الاشتراكات',
      'monthly_tasks': 'مهام الشهر',
      'dashboard_high_priority': 'المشاريع عالية الأولوية',
      'dashboard_today_tasks': 'مهام اليوم',
      'dashboard_focus_hours': 'ساعات التركيز',
      'dashboard_focus_title': 'رؤى التركيز',
      'dashboard_focus_week_label': 'هذا الأسبوع',
      'dashboard_focus_total_label': 'إجمالي الوقت',
      'dashboard_focus_top_task': 'أكثر مهمة تركيزاً · {task}',
      'dashboard_focus_top_task_empty': 'سجل جلسة لكشف المهمة الأكثر تركيزاً.',
      'dashboard_focus_last': 'آخر تركيز {duration} · {time}',
      'dashboard_focus_last_empty': 'لم يتم تسجيل أي جلسات تركيز بعد.',
      'tasks_today': 'اليوم',
      'tasks_calendar': 'التقويم',
      'tasks_total': 'إجمالي المهام',
      'tasks_average': 'متوسط يومي',
      'tasks_hours': 'إجمالي الساعات',
      'search_tasks_hint': 'بحث في المهام',
      'scheduler_title': 'جدول المواعيد',
      'scheduler_subtitle': 'رتب يومك بمساحات تركيز ذات طابع.',
      'scheduler_add_block': 'إضافة كتلة',
      'scheduler_new_block': 'كتلة مجدولة جديدة',
      'scheduler_title_field': 'العنوان',
      'scheduler_description_field': 'الوصف',
      'scheduler_pick_time': 'اختر وقت البدء',
      'scheduler_duration_option': '{minutes} دقيقة',
      'scheduler_save': 'حفظ الكتلة',
      'scheduler_validation_title': 'أدخل عنواناً للكتلة أولاً.',
      'scheduler_created_success': 'تمت إضافة الكتلة إلى يومك.',
      'scheduler_empty': 'لا توجد جلسات مخططة. أضف كتلة التركيز التالية.',
      'scheduler_removed': 'تم حذف الكتلة من الجدول.',
      'scheduler_tag_focus': 'تركيز',
      'scheduler_tag_team': 'فريق',
      'scheduler_tag_client': 'عميل',
      'scheduler_tag_deep_work': 'عمل عميق',
      'task_details_schedule': 'الجدول',
      'task_due_date': 'تاريخ الاستحقاق {date}',
      'task_details_description': 'الوصف',
      'task_details_hours': 'الساعات المقدرة',
      'task_details_mark_done': 'وضع علامة كمكتمل',
      'task_details_mark_active': 'وضع علامة كنشط',
      'task_details_marked_done': 'تم وضع علامة على المهمة كمكتملة',
      'task_details_marked_active': 'تمت إعادة المهمة كفعّالة',
      'task_overlay_front': 'معاينة للمهمة، اضغط للانقلاب ورؤية التفاصيل.',
      'filter_status': 'الحالة',
      'status_in_progress': 'قيد التنفيذ',
      'status_upcoming': 'قادمة',
      'status_done': 'منتهية',
      'load_more': 'تحميل المزيد',
      'catalog_search_hint': 'بحث في الكتالوج',
      'type_template': 'قالب',
      'type_document': 'مستند',
      'type_task': 'مهمة',
      'view_list': 'قائمة',
      'view_grid': 'شبكة',
      'compare_selected_full': 'مقارنة العناصر المختارة ({count})',
      'language_en': 'الإنجليزية',
      'language_ar': 'العربية',
      'primary_color': 'اللون الأساسي',
      'templates_title': 'القوالب',
      'templates_subtitle': 'وفر الوقت مع اللبنات الجاهزة.',
      'templates_search_hint': 'بحث في القوالب',
      'templates_hours': '{hours} ساعة تقديرية',
      'templates_added_to_catalog': 'تمت إضافة القالب إلى الكتالوج.',
      'templates_add_to_catalog': 'إضافة إلى الكتالوج',
      'templates_popular': 'شائع',
      'library_title': 'مكتبتي',
      'library_subtitle': 'مستندات وعروض وملاحظات في لمحة.',
      'library_search_hint': 'بحث في المكتبة',
      'library_link_copied': 'تم نسخ الرابط للمشاركة السريعة.',
      'time_tracker_title': 'متعقب الوقت',
      'time_tracker_subtitle': 'سجل جلسات التركيز بأناقة باستيل.',
      'time_tracker_task_label': 'المهمة المرتبطة',
      'time_tracker_no_task': 'جلسة غير مرتبطة',
      'time_tracker_last_session': 'آخر جلسة',
      'time_tracker_last_session_time': 'تم التسجيل في {time}',
      'time_tracker_last_session_empty': 'لم يتم تسجيل أي جلسات بعد.',
      'time_tracker_reset': 'إعادة ضبط',
      'time_tracker_start': 'بدء',
      'time_tracker_pause': 'إيقاف مؤقت',
      'time_tracker_stop': 'إيقاف',
      'time_tracker_logged': 'تم تسجيل الجلسة بنجاح.',
      'time_tracker_summary_title': 'ملخص التركيز',
      'time_tracker_weekly_total': '{duration} مسجلة هذا الأسبوع',
      'time_tracker_total': '{duration} مسجلة إجمالاً',
      'time_tracker_top_task': 'أكثر مهمة تركيزاً · {task}',
      'time_tracker_top_task_empty': 'سجل جلسة لإظهار المهمة الأكثر تركيزاً.',
      'time_tracker_history': 'سجل الجلسات',
      'time_tracker_history_empty': 'لا توجد جلسات تركيز بعد. ابدأ واحدة لبناء الزخم.',
      'time_tracker_clear_history': 'مسح السجل',
      'time_tracker_session_at': 'تم التسجيل في {time}',
      'time_tracker_history_cleared': 'تم مسح سجل الجلسات.',
      'dark_mode': 'الوضع الداكن',
      'profile_trial': 'تنتهي الفترة التجريبية بعد {days} يومًا',
      'invalid_email': 'يرجى إدخال بريد إلكتروني صحيح',
      'required_field': 'هذا الحقل مطلوب',
      'password_too_short': 'يجب أن لا تقل كلمة المرور عن 6 أحرف',
      'password_mismatch': 'كلمتا المرور غير متطابقتين',
      'email_address': 'البريد الإلكتروني',
      'full_name': 'الاسم الكامل',
      'confirm_password': 'تأكيد كلمة المرور',
      'password_strength': 'قوة كلمة المرور',
      'search_global_hint': 'ابحث عن أي شيء',
      'search_results_projects': 'المشاريع',
      'search_results_tasks': 'المهام',
      'search_results_catalog': 'الكتالوج',
      'search_results_templates': 'القوالب',
      'drawer_trial': 'تجريبي',
      'settings_profile': 'تفاصيل الحساب',
      'settings_subscription': 'خطة الاشتراك',
      'settings_brand': 'عناصر الهوية',
      'settings_bank': 'الحساب البنكي',
      'ai_future_title': 'قريباً',
      'ai_future_message': 'سيتوفر مساعد الذكاء الاصطناعي في إصدار لاحق.'
    }
  };

  String translate(String key, {Map<String, String>? params}) {
    var value = _localizedValues[locale.languageCode]?[key] ?? key;
    if (params != null) {
      params.forEach((placeholder, replacement) {
        value = value.replaceAll('{$placeholder}', replacement);
      });
    }
    return value;
  }

  TextDirection get textDirection => locale.languageCode == 'ar' ? TextDirection.rtl : TextDirection.ltr;

  static AppLocalizations of(BuildContext context) => Localizations.of<AppLocalizations>(context, AppLocalizations)!;
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => AppLocalizations.supportedLocales.any((l) => l.languageCode == locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async => AppLocalizations(locale);

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}
