import 'package:flutter/material.dart';

class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;

  static const supportedLocales = [Locale('en'), Locale('ar')];

  static const _localizedValues = {
    'en': {
      'app_title': 'ConnecQ Productivity OS',
      'skip': 'Skip',
      'next': 'Next',
      'get_started': 'Get Started',
      'login': 'Login',
      'login_guest': 'Login as guest',
      'email': 'Email address',
      'password': 'Password',
      'forgot_password': 'Forgot password?',
      'register': 'Register',
      'dashboard': 'Dashboard',
      'projects': 'Projects',
      'tasks': 'Tasks',
      'calendar': 'Calendar',
      'calendar_overview': 'Monthly overview',
      'calendar_selected_day': 'Tasks for {date}',
      'calendar_empty': 'No tasks scheduled for this day.',
      'calendar_previous_month': 'Previous month',
      'calendar_next_month': 'Next month',
      'finance': 'Finance Overview',
      'finance_overview_subtitle': 'Track revenue, expenses, and invoices at a glance',
      'finance_tab_monthly': 'Monthly',
      'finance_tab_yearly': 'Yearly',
      'finance_summary_revenue': 'Revenue',
      'finance_summary_expenses': 'Expenses',
      'finance_summary_outstanding': 'Outstanding',
      'finance_summary_net': 'Net income',
      'finance_highlight_monthly': 'Strongest performing month',
      'finance_highlight_yearly': 'Top performing year',
      'finance_highlight_trend': '{percent}% vs previous period',
      'finance_progress_to_goal': 'to goal',
      'finance_chart_monthly': 'Revenue by month',
      'finance_chart_yearly': 'Revenue by year',
      'finance_bar_revenue': 'Revenue',
      'finance_bar_expenses': 'Expenses',
      'finance_invoices_section': 'Invoices spotlight',
      'finance_invoices_upcoming': 'Upcoming invoices',
      'finance_invoices_overdue': 'Overdue invoices',
      'finance_invoices_empty': 'No invoices to show right now.',
      'finance_invoices_all': 'All invoices',
      'finance_invoices_filter_label': 'Filter invoices',
      'finance_filter_all': 'All',
      'finance_filter_due': 'Due',
      'finance_filter_overdue': 'Overdue',
      'finance_filter_paid': 'Paid',
      'finance_invoice_status_due': 'Due',
      'finance_invoice_status_overdue': 'Overdue',
      'finance_invoice_status_paid': 'Paid',
      'finance_invoice_due_date': 'Due {date}',
      'finance_invoice_overdue_date': 'Overdue since {date}',
      'finance_invoice_paid_date': 'Paid on {date}',
      'finance_invoice_mark_paid': 'Mark as paid',
      'finance_load_more_invoices': 'Load more invoices',
      'finance_dashboard_outstanding': 'Outstanding: \${amount}',
      'tools': 'Tools',
      'tools_subtitle': 'Quick access to productivity spaces',
      'tools_calendar': 'Calendar planner',
      'tools_calendar_subtitle': 'Plan your month with highlights',
      'tools_scheduler': 'Scheduler',
      'tools_scheduler_empty': 'No events scheduled today',
      'tools_templates': 'Templates',
      'tools_templates_count': '{count} templates curated',
      'tools_library': 'Library',
      'tools_library_count': '{count} knowledge items',
      'tools_insights': 'Workspace insights',
      'tools_insights_summary_zero': '{rate}% · no deadlines',
      'tools_insights_summary_one': '{rate}% · 1 deadline',
      'tools_insights_summary_many': '{rate}% · {count} deadlines',
      'tools_time_tracker': 'Time tracker',
      'tools_time_tracker_subtitle': '{last} last focus · {week} this week',
      'tools_tasks': 'All tasks',
      'tools_tasks_subtitle': 'Jump to your task board',
      'tools_spotlight_templates': 'Spotlight templates',
      'tools_recent_library': 'Recently updated library',
      'tools_goals_summary': '{tasks}% tasks · {focus}% focus',
      'tools_team': 'Team',
      'tools_team_subtitle': '{active} active · {favorites} starred',
      'tools_team_activity': 'Last check-in with {name} · {time}',
      'workspace_goals': 'Workspace goals',
      'workspace_goals_subtitle': 'Align your task, revenue, and focus targets',
      'workspace_goals_loading': 'Syncing progress...',
      'workspace_goals_tasks_title': 'Monthly tasks',
      'workspace_goals_revenue_title': 'Monthly revenue',
      'workspace_goals_focus_title': 'Weekly focus',
      'workspace_goals_value_of_goal': '{value}/{goal}',
      'workspace_goals_currency_value': '\${value} / \${goal}',
      'workspace_goals_progress_caption': '{percent}% complete',
      'workspace_goals_target_tasks': 'Target {count} tasks',
      'workspace_goals_target_revenue': 'Target \$ {amount}',
      'workspace_goals_target_focus': 'Target {hours}h',
      'workspace_goals_focus_value': '{hours}h {minutes}m',
      'workspace_goals_focus_value_hours': '{hours}h',
      'workspace_goals_edit': 'Adjust goals',
      'workspace_goals_edit_title': 'Adjust workspace goals',
      'workspace_goals_edit_description': 'Tune your targets to match the current plan.',
      'workspace_goals_tasks_label': 'Monthly tasks target',
      'workspace_goals_revenue_label': 'Revenue goal (USD)',
      'workspace_goals_focus_label': 'Weekly focus hours',
      'workspace_goals_cancel': 'Cancel',
      'workspace_goals_save': 'Save goals',
      'workspace_goals_saved': 'Goals updated',
      'workspace_goals_focus_gap': '{hours}h {minutes}m remaining',
      'workspace_goals_tasks_gap': '{count} tasks remaining',
      'workspace_goals_revenue_gap': '\$ {amount} remaining',
      'workspace_goals_goal_met': 'Goal reached',
      'catalog': 'Catalog',
      'clients': 'Clients',
      'clients_subtitle': 'Track relationships and deal flow with clarity',
      'clients_pipeline_value': 'Pipeline value',
      'clients_active_clients': 'Active clients',
      'clients_starred_clients': 'Starred',
      'clients_search_hint': 'Search clients by name or company',
      'clients_stage_all': 'All',
      'clients_stage_prospect': 'Prospect',
      'clients_stage_contacted': 'Contacted',
      'clients_stage_proposal': 'Proposal',
      'clients_stage_negotiation': 'Negotiation',
      'clients_stage_won': 'Won',
      'clients_stage_lost': 'Lost',
      'clients_empty_state': 'No clients match this filter yet.',
      'clients_load_more': 'Load more clients',
      'clients_last_contact': 'Last contact {value}',
      'clients_last_contact_now': 'just now',
      'clients_last_contact_minutes': '{minutes}m ago',
      'clients_last_contact_today': 'today at {time}',
      'clients_last_contact_yesterday': 'yesterday at {time}',
      'clients_last_contact_days': '{days}d ago',
      'clients_last_contact_date': 'on {date}',
      'clients_stage_updated': 'Client stage updated',
      'clients_interaction_title': 'Log interaction',
      'clients_interaction_type_label': 'Interaction type',
      'clients_interaction_type_call': 'Call',
      'clients_interaction_type_email': 'Email',
      'clients_interaction_type_meeting': 'Meeting',
      'clients_interaction_note_hint': 'Add a quick note about this touchpoint',
      'clients_interaction_note_error': 'Please add a short note.',
      'clients_interaction_logged': 'Interaction logged',
      'clients_interaction_save': 'Save interaction',
      'clients_form_title': 'Add new client',
      'clients_form_name': 'Client name',
      'clients_form_name_error': 'Add the client name.',
      'clients_form_company': 'Company',
      'clients_form_company_error': 'Add the company name.',
      'clients_form_stage': 'Stage',
      'clients_form_value': 'Pipeline value (USD)',
      'clients_form_email': 'Email',
      'clients_form_phone': 'Phone',
      'clients_form_tags_hint': 'Tags (comma separated)',
      'clients_form_notes': 'Notes',
      'clients_form_cancel': 'Cancel',
      'clients_form_save': 'Save client',
      'clients_form_created': 'Client added',
      'team': 'Team',
      'team_subtitle': 'Coordinate roles, focus, and availability',
      'team_summary_members': 'Members',
      'team_summary_active': 'Active now',
      'team_summary_focus': 'Avg focus',
      'team_summary_checkins': 'Check-ins this week',
      'team_summary_favorites': '{count} starred',
      'team_summary_overview': '{active} of {total} teammates active today',
      'team_search_hint': 'Search teammates by name, role, or skill',
      'team_filter_all': 'All',
      'team_status_active': 'Active',
      'team_status_onboarding': 'Onboarding',
      'team_status_out_of_office': 'Out of office',
      'team_status_contractor': 'Contractor',
      'team_highlight_title': 'Standout collaborators',
      'team_highlight_empty': 'Highlight teammates by starring them or setting focus goals.',
      'team_highlight_placeholder': 'Star teammates or update their status to spotlight them here.',
      'team_add_button': 'Add teammate',
      'team_add_title': 'Invite new teammate',
      'team_add_name': 'Full name',
      'team_add_name_error': 'Enter the teammate name.',
      'team_add_role': 'Role',
      'team_add_role_error': 'Enter the role.',
      'team_add_status': 'Status',
      'team_add_email': 'Email (optional)',
      'team_add_location': 'Location (optional)',
      'team_add_timezone': 'Timezone (optional)',
      'team_add_focus_hours': 'Weekly focus target (hours)',
      'team_add_tasks': 'Weekly tasks goal',
      'team_add_skills': 'Skills (comma separated)',
      'team_add_cancel': 'Cancel',
      'team_add_save': 'Add teammate',
      'team_add_success': 'Teammate added',
      'team_favorite_added': 'Added to favorites',
      'team_favorite_removed': 'Removed from favorites',
      'team_status_updated': 'Status updated',
      'team_empty_state': 'No teammates match this filter yet.',
      'team_load_more': 'Load more teammates',
      'team_focus_hours': '{hours}h focus',
      'team_tasks_this_week': '{count} tasks this week',
      'team_member_since': 'Joined {date}',
      'team_capacity_label': '{percent}% capacity',
      'team_capacity_average': 'Avg capacity {percent}%',
      'team_last_active_label': 'Last active',
      'team_last_active_now': 'just now',
      'team_last_active_minutes': '{minutes}m ago',
      'team_last_active_hours': '{hours}h ago',
      'team_last_active_yesterday': 'yesterday at {time}',
      'team_last_active_days': '{days}d ago',
      'team_last_active_date': 'on {date}',
      'team_spotlight_tasks': 'tasks this week',
      'team_recent_check_in_title': 'Latest team check-in',
      'team_recent_check_in_empty': 'Log a quick update to spotlight momentum.',
      'team_recent_check_in_cta': 'View timeline',
      'team_recent_check_in_log': 'Log check-in',
      'team_recent_check_in_by': 'Logged by {author}',
      'team_recent_check_in_time': 'Updated {time}',
      'team_recent_check_in_sentiment_positive': 'Positive energy',
      'team_recent_check_in_sentiment_neutral': 'Steady progress',
      'team_recent_check_in_sentiment_attention': 'Needs attention',
      'team_details_activity_timeline': 'Check-in timeline',
      'team_details_check_ins_empty': 'No check-ins yet. Log the first update.',
      'team_details_check_in_add': 'Log check-in',
      'team_details_check_in_sheet_title': 'Log team check-in',
      'team_details_check_in_summary': 'Summary',
      'team_details_check_in_summary_hint': 'How is this teammate doing?',
      'team_details_check_in_summary_error': 'Add a short summary.',
      'team_details_check_in_sentiment': 'Sentiment',
      'team_details_sentiment_positive': 'Positive',
      'team_details_sentiment_neutral': 'Neutral',
      'team_details_sentiment_attention': 'Needs attention',
      'team_details_check_in_highlights': 'Highlights (comma separated)',
      'team_details_check_in_next_steps': 'Next steps (comma separated)',
      'team_details_check_in_cancel': 'Cancel',
      'team_details_check_in_save': 'Save check-in',
      'team_details_check_in_success': 'Check-in saved',
      'team_details_check_in_highlights_label': 'Highlights',
      'team_details_check_in_next_label': 'Next steps',
      'team_details_contact_section': 'Contact',
      'team_details_contact_email': 'Email',
      'team_details_contact_location': 'Location',
      'team_details_contact_timezone': 'Timezone',
      'team_details_skillset': 'Skillset',
      'team_details_logged_by': 'Logged by {author}',
      'clients_add_button': 'Add client',
      'clients_log_interaction': 'Log interaction',
      'clients_change_stage': 'Change stage',
      'clients_view_all': 'View all',
      'clients_spotlight_title': 'Spotlight deals',
      'clients_pipeline_focus': '{count} high-engagement deals',
      'clients_pipeline_starred': '{count} starred',
      'dashboard_clients_card_title': 'Client relationships',
      'dashboard_clients_card_subtitle': '{count} active · \${value} pipeline',
      'tools_clients': 'Client CRM',
      'tools_clients_subtitle': '{count} active relationships',
      'search_results_clients': 'Clients',
      'compare': 'Compare',
      'search': 'Search',
      'notifications': 'Notifications',
      'notifications_with_count': 'Notifications ({count})',
      'notifications_empty': 'You are all caught up for now!',
      'notifications_mark_all_read': 'Mark all read',
      'notifications_clear_all': 'Clear all',
      'notifications_section_pinned': 'Pinned',
      'notifications_section_recent': 'Recent updates',
      'notifications_mark_read': 'Mark as read',
      'notifications_mark_unread': 'Mark as unread',
      'notifications_pin': 'Pin to top',
      'notifications_unpin': 'Unpin',
      'project_linked_tasks': 'Linked tasks',
      'project_progress': 'Progress {percent}%',
      'mark_completed': 'Mark as completed',
      'mark_active': 'Mark as active',
      'add_to_compare': 'Add to compare',
      'remove_from_compare': 'Remove from compare',
      'project_no_tasks': 'No related tasks yet.',
      'settings': 'Settings',
      'theme': 'Theme',
      'language': 'Language',
      'dark_mode': 'Dark Mode',
      'primary_color': 'Primary color',
      'ai_placeholder': 'AI assistant will be available in a future version.',
      'done': 'Done',
      'refreshing': 'Refreshing data...',
      'good_morning': 'Good morning, {name}',
      'onboarding_title_1': 'Organize your work beautifully',
      'onboarding_desc_1': 'Stay in control of projects, tasks and resources in a single flow.',
      'onboarding_title_2': 'Collaborate in pastel calm',
      'onboarding_desc_2': 'Share progress with your team in a soft, minimal dashboard.',
      'onboarding_title_3': 'Plan smarter with ConnecQ',
      'onboarding_desc_3': 'Track time, finances and catalog assets without friction.',
      'projects_subtitle': 'Your running initiatives',
      'projects_add_button': 'New project',
      'projects_create_title': 'Create project',
      'projects_field_title': 'Project title',
      'projects_field_priority': 'Priority',
      'projects_field_status': 'Status',
      'projects_field_due_date': 'Due date',
      'projects_field_hours': 'Estimated hours',
      'projects_field_progress': 'Progress',
      'projects_field_tags': 'Tags',
      'projects_tags_hint': 'marketing, design',
      'projects_create_action': 'Save project',
      'projects_validation_title': 'Give the project a name first.',
      'projects_validation_hours': 'Enter a valid hour estimate.',
      'projects_validation_due': 'Pick a due date to schedule the project.',
      'projects_due_placeholder': 'Select due date',
      'projects_created_success': 'Project added to your workspace.',
      'project_status_planning': 'Planning',
      'project_status_in_progress': 'In progress',
      'project_status_in_review': 'In review',
      'project_status_blocked': 'Blocked',
      'project_status_completed': 'Completed',
      'search_projects_hint': 'Search projects',
      'filter_all': 'All',
      'priority_high': 'High',
      'priority_medium': 'Medium',
      'priority_low': 'Low',
      'compare_selected': 'Compare ({count})',
      'compare_header': 'Compare items',
      'compare_empty': 'Select up to three items to compare them side by side.',
      'clear_compare': 'Clear comparison list',
      'compare_type': 'Type',
      'compare_priority': 'Priority',
      'compare_status': 'Status',
      'compare_estimate': 'Estimated time',
      'compare_due': 'Due date',
      'payment_summary': 'Payment summary',
      'payment_invoices': 'Invoices',
      'payment_subscriptions': 'Subscriptions',
      'monthly_tasks': 'Monthly tasks',
      'dashboard_high_priority': 'High priority projects',
      'dashboard_today_tasks': 'Today tasks',
      'dashboard_focus_hours': 'Focus hours',
      'dashboard_team_pulse_title': 'Team pulse',
      'dashboard_team_view_all': 'View team',
      'dashboard_team_pulse_active': '{count} active today',
      'dashboard_team_pulse_focus': 'Avg focus {hours}h',
      'dashboard_team_pulse_highlight': 'Spotlight: {name}',
      'dashboard_team_recent_check_in': 'Latest check-in · {name}',
      'dashboard_team_recent_check_in_time': 'Logged {time}',
      'dashboard_focus_title': 'Focus insights',
      'dashboard_focus_week_label': 'This week',
      'dashboard_focus_total_label': 'All time',
      'dashboard_focus_top_task': 'Top task · {task}',
      'dashboard_focus_top_task_empty': 'Track a session to reveal your top task.',
      'dashboard_focus_last': 'Last focus {duration} · {time}',
      'dashboard_focus_last_empty': 'No focus sessions logged yet.',
      'dashboard_insights_card_title': 'Workspace health',
      'insights_open_button': 'View insights',
      'insights_completion_rate': 'Completion rate',
      'insights_focus_hours': 'Weekly focus',
      'insights_net_income': 'Net income',
      'insights_outstanding_label': 'Outstanding {value}',
      'insights_deadline_section': 'Upcoming deadlines',
      'insights_deadline_none': 'No deadlines in the next few days.',
      'insights_deadline_project': 'Project',
      'insights_deadline_task': 'Task',
      'insights_deadline_due_today': 'Due today',
      'insights_deadline_due_tomorrow': 'Due tomorrow',
      'insights_deadline_due_in': 'Due in {days} days',
      'insights_weekly_completion': 'Weekly completion trend',
      'insights_weekly_empty': 'No scheduled work this week yet.',
      'insights_priority_mix': 'Priority mix',
      'insights_priority_empty': 'No priority insights yet.',
      'insights_focus_breakdown': 'Focus breakdown',
      'insights_focus_empty': 'Log focus sessions to unlock breakdowns.',
      'insights_focus_hours_short': '{hours}h',
      'insights_focus_minutes_short': '{minutes}m',
      'insights_focus_unassigned': 'Unassigned focus',
      'insights_recent_sessions': 'Recent focus sessions',
      'insights_sessions_empty': 'Track a session to see history here.',
      'insights_title': 'Workspace insights',
      'tasks_add_button': 'New task',
      'tasks_create_title': 'Create task',
      'tasks_field_title': 'Task title',
      'tasks_field_category': 'Category',
      'tasks_field_description': 'Description',
      'tasks_field_priority': 'Priority',
      'tasks_field_status': 'Status',
      'tasks_field_due_date': 'Due date',
      'tasks_field_hours': 'Estimated hours',
      'tasks_create_action': 'Save task',
      'tasks_validation_due': 'Pick a due date to schedule the task.',
      'tasks_due_placeholder': 'Select due date',
      'tasks_created_success': 'Task added to your list.',
      'tasks_today': 'Today',
      'tasks_calendar': 'Calendar',
      'tasks_total': 'Total tasks',
      'tasks_average': 'Avg per day',
      'tasks_hours': 'Total hours',
      'search_tasks_hint': 'Search tasks',
      'scheduler_title': 'Scheduler',
      'scheduler_subtitle': 'Layer your day with themed sessions.',
      'scheduler_add_block': 'Add block',
      'scheduler_new_block': 'New schedule block',
      'scheduler_title_field': 'Title',
      'scheduler_description_field': 'Description',
      'scheduler_pick_time': 'Pick start time',
      'scheduler_duration_option': '{minutes} minutes',
      'scheduler_save': 'Save block',
      'scheduler_validation_title': 'Give the block a title first.',
      'scheduler_created_success': 'Schedule block added to your day.',
      'scheduler_empty': 'No sessions planned. Add your next focus block.',
      'scheduler_removed': 'Schedule block removed.',
      'scheduler_tag_focus': 'Focus',
      'scheduler_tag_team': 'Team',
      'scheduler_tag_client': 'Client',
      'scheduler_tag_deep_work': 'Deep work',
      'task_details_schedule': 'Schedule',
      'task_due_date': 'Due {date}',
      'task_details_description': 'Description',
      'task_details_hours': 'Estimated hours',
      'task_details_mark_done': 'Mark as done',
      'task_details_mark_active': 'Mark as active',
      'task_details_marked_done': 'Task marked as done',
      'task_details_marked_active': 'Task set back to active',
      'task_overlay_front': 'Preview asset. Tap to flip for details.',
      'filter_status': 'Status',
      'status_in_progress': 'In progress',
      'status_upcoming': 'Upcoming',
      'status_done': 'Done',
      'load_more': 'Load more',
      'catalog_search_hint': 'Search catalog',
      'type_template': 'Template',
      'type_document': 'Document',
      'type_task': 'Task',
      'view_list': 'List',
      'view_grid': 'Grid',
      'catalog_add_to_compare': 'Add to compare',
      'catalog_remove_from_compare': 'Remove from compare',
      'catalog_open_compare': 'Open compare board',
      'catalog_estimated_hours': '{hours}h estimate',
      'catalog_highlights_title': 'Comparison highlights',
      'catalog_highlight_priority': 'Priority • {priority}',
      'catalog_highlight_type': 'Category • {type}',
      'catalog_highlight_tags': 'Tags • {tags}',
      'catalog_highlight_hours': 'Effort • {hours}h',
      'catalog_flip_hint': 'Tap the card to flip and explore more context.',
      'catalog_flip_button_front': 'View highlights',
      'catalog_flip_button_back': 'Back to details',
      'catalog_compare_snackbar_added': 'Added to compare',
      'catalog_compare_snackbar_removed': 'Removed from compare',
      'compare_selected_full': 'Compare selected ({count})',
      'language_en': 'English',
      'language_ar': 'Arabic',
      'settings_goals_subtitle': 'Update targets for the dashboard',
      'primary_color': 'Primary color',
      'templates_title': 'Templates',
      'templates_subtitle': 'Save time with curated building blocks.',
      'templates_search_hint': 'Search templates',
      'templates_hours': '{hours}h estimate',
      'templates_added_to_catalog': 'Template added to your catalog.',
      'templates_add_to_catalog': 'Add to catalog',
      'templates_popular': 'Popular',
      'library_title': 'My Library',
      'library_subtitle': 'Documents, decks, and notes at a glance.',
      'library_search_hint': 'Search library',
      'library_link_copied': 'Link copied for quick sharing.',
      'time_tracker_title': 'Time tracker',
      'time_tracker_subtitle': 'Capture deep work sessions in pastel focus.',
      'time_tracker_task_label': 'Linked task',
      'time_tracker_no_task': 'Unassigned session',
      'time_tracker_last_session': 'Last session',
      'time_tracker_last_session_time': 'Logged {time}',
      'time_tracker_last_session_empty': 'No sessions logged yet.',
      'time_tracker_reset': 'Reset',
      'time_tracker_start': 'Start',
      'time_tracker_pause': 'Pause',
      'time_tracker_stop': 'Stop',
      'time_tracker_logged': 'Session logged successfully.',
      'time_tracker_summary_title': 'Focus summary',
      'time_tracker_weekly_total': '{duration} tracked this week',
      'time_tracker_total': '{duration} logged overall',
      'time_tracker_top_task': 'Most focused · {task}',
      'time_tracker_top_task_empty': 'Log a session to surface your top task.',
      'time_tracker_history': 'Session history',
      'time_tracker_history_empty': 'No focus sessions yet. Start one to build momentum.',
      'time_tracker_clear_history': 'Clear history',
      'time_tracker_session_at': 'Logged {time}',
      'time_tracker_history_cleared': 'Session history cleared.',
      'dark_mode': 'Dark Mode',
      'profile_trial': 'Trial ends in {days} days',
      'invalid_email': 'Please enter a valid email',
      'required_field': 'This field is required',
      'password_too_short': 'Password must be at least 6 characters',
      'password_mismatch': 'Passwords do not match',
      'email_address': 'Email address',
      'full_name': 'Full name',
      'confirm_password': 'Confirm password',
      'password_strength': 'Password strength',
      'search_global_hint': 'Search anything',
      'search_results_projects': 'Projects',
      'search_results_tasks': 'Tasks',
      'search_results_catalog': 'Catalog',
      'search_results_templates': 'Templates',
      'search_results_team': 'Team',
      'search_history': 'Recent searches',
      'search_clear_history': 'Clear history',
      'search_empty_history': 'Start exploring to build your search history.',
      'drawer_trial': 'Trial',
      'settings_profile': 'Account details',
      'settings_subscription': 'Subscription plan',
      'settings_brand': 'Brand elements',
      'settings_bank': 'Bank account',
      'ai_future_title': 'Coming soon',
      'ai_future_message': 'AI assistant will be available in a future version.'
    },
    'ar': {
      'app_title': 'نظام كونيك كيو للإنتاجية',
      'skip': 'تخطي',
      'next': 'التالي',
      'get_started': 'ابدأ الآن',
      'login': 'تسجيل الدخول',
      'login_guest': 'الدخول كضيف',
      'email': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'forgot_password': 'هل نسيت كلمة المرور؟',
      'register': 'إنشاء حساب',
      'dashboard': 'لوحة التحكم',
      'projects': 'المشاريع',
      'tasks': 'المهام',
      'calendar': 'التقويم',
      'calendar_overview': 'نظرة شهرية',
      'calendar_selected_day': 'مهام يوم {date}',
      'calendar_empty': 'لا توجد مهام مجدولة لهذا اليوم.',
      'calendar_previous_month': 'الشهر السابق',
      'calendar_next_month': 'الشهر التالي',
      'finance': 'نظرة مالية',
      'finance_overview_subtitle': 'تابع الإيرادات والمصروفات والفواتير في لمحة',
      'finance_tab_monthly': 'شهري',
      'finance_tab_yearly': 'سنوي',
      'finance_summary_revenue': 'الإيرادات',
      'finance_summary_expenses': 'المصروفات',
      'finance_summary_outstanding': 'المستحقات',
      'finance_summary_net': 'صافي الدخل',
      'finance_highlight_monthly': 'أفضل شهر أداءً',
      'finance_highlight_yearly': 'أفضل سنة أداءً',
      'finance_highlight_trend': '{percent}% مقارنة بالفترة السابقة',
      'finance_progress_to_goal': 'إلى الهدف',
      'finance_chart_monthly': 'الإيرادات حسب الشهر',
      'finance_chart_yearly': 'الإيرادات حسب السنة',
      'finance_bar_revenue': 'الإيرادات',
      'finance_bar_expenses': 'المصروفات',
      'finance_invoices_section': 'أضواء على الفواتير',
      'finance_invoices_upcoming': 'الفواتير القادمة',
      'finance_invoices_overdue': 'الفواتير المتأخرة',
      'finance_invoices_empty': 'لا توجد فواتير للعرض الآن.',
      'finance_invoices_all': 'جميع الفواتير',
      'finance_invoices_filter_label': 'تصفية الفواتير',
      'finance_filter_all': 'الكل',
      'finance_filter_due': 'مستحقة',
      'finance_filter_overdue': 'متأخرة',
      'finance_filter_paid': 'مدفوعة',
      'finance_invoice_status_due': 'مستحقة',
      'finance_invoice_status_overdue': 'متأخرة',
      'finance_invoice_status_paid': 'مدفوعة',
      'finance_invoice_due_date': 'تستحق في {date}',
      'finance_invoice_overdue_date': 'متأخرة منذ {date}',
      'finance_invoice_paid_date': 'دُفعت في {date}',
      'finance_invoice_mark_paid': 'تمييز كمدفوعة',
      'finance_load_more_invoices': 'تحميل المزيد من الفواتير',
      'finance_dashboard_outstanding': 'المستحقات: \${amount}',
      'tools': 'الأدوات',
      'tools_subtitle': 'وصول سريع لمساحات الإنتاجية',
      'tools_calendar': 'مخطط التقويم',
      'tools_calendar_subtitle': 'خطط شهرك مع النقاط المضيئة',
      'tools_scheduler': 'جدول المواعيد',
      'tools_scheduler_empty': 'لا توجد جلسات مجدولة اليوم',
      'tools_templates': 'القوالب',
      'tools_templates_count': '{count} قالب منسق',
      'tools_library': 'المكتبة',
      'tools_library_count': '{count} عنصر معرفي',
      'tools_insights': 'تحليلات مساحة العمل',
      'tools_insights_summary_zero': '{rate}% · بلا مواعيد',
      'tools_insights_summary_one': '{rate}% · موعد واحد',
      'tools_insights_summary_many': '{rate}% · {count} مواعيد',
      'tools_time_tracker': 'متعقب الوقت',
      'tools_time_tracker_subtitle': '{last} في آخر جلسة · {week} هذا الأسبوع',
      'tools_tasks': 'جميع المهام',
      'tools_tasks_subtitle': 'انتقل مباشرة إلى لوحة المهام',
      'tools_spotlight_templates': 'قوالب مميزة',
      'tools_recent_library': 'مكتبة محدثة مؤخراً',
      'tools_goals_summary': '{tasks}% مهام · {focus}% تركيز',
      'tools_team': 'الفريق',
      'tools_team_subtitle': '{active} نشط · {favorites} مميز',
      'tools_team_activity': 'آخر متابعة مع {name} · {time}',
      'workspace_goals': 'أهداف مساحة العمل',
      'workspace_goals_subtitle': 'اضبط أهداف المهام والإيرادات والتركيز.',
      'workspace_goals_loading': 'جاري مزامنة التقدم...',
      'workspace_goals_tasks_title': 'مهام شهرية',
      'workspace_goals_revenue_title': 'إيراد شهري',
      'workspace_goals_focus_title': 'تركيز أسبوعي',
      'workspace_goals_value_of_goal': '{value}/{goal}',
      'workspace_goals_currency_value': '\${value} / \${goal}',
      'workspace_goals_progress_caption': '{percent}% منجز',
      'workspace_goals_target_tasks': 'الهدف {count} مهمة',
      'workspace_goals_target_revenue': 'الهدف \$ {amount}',
      'workspace_goals_target_focus': 'الهدف {hours}س',
      'workspace_goals_focus_value': '{hours}س {minutes}د',
      'workspace_goals_focus_value_hours': '{hours}س',
      'workspace_goals_edit': 'تعديل الأهداف',
      'workspace_goals_edit_title': 'تعديل أهداف مساحة العمل',
      'workspace_goals_edit_description': 'قم بضبط الأهداف لتتلاءم مع الخطة الحالية.',
      'workspace_goals_tasks_label': 'الهدف الشهري للمهام',
      'workspace_goals_revenue_label': 'هدف الإيراد (دولار أمريكي)',
      'workspace_goals_focus_label': 'ساعات التركيز الأسبوعية',
      'workspace_goals_cancel': 'إلغاء',
      'workspace_goals_save': 'حفظ الأهداف',
      'workspace_goals_saved': 'تم تحديث الأهداف',
      'workspace_goals_focus_gap': 'متبقي {hours}س {minutes}د',
      'workspace_goals_tasks_gap': 'متبقي {count} مهمة',
      'workspace_goals_revenue_gap': 'متبقي \$ {amount}',
      'workspace_goals_goal_met': 'تم تحقيق الهدف',
      'catalog': 'كتالوج',
      'clients': 'العملاء',
      'clients_subtitle': 'إدارة العلاقات وتدفق الصفقات بسلاسة',
      'clients_pipeline_value': 'قيمة الصفقات',
      'clients_active_clients': 'عملاء نشطون',
      'clients_starred_clients': 'مميزون',
      'clients_search_hint': 'ابحث عن العملاء بالاسم أو الشركة',
      'clients_stage_all': 'الكل',
      'clients_stage_prospect': 'عميل محتمل',
      'clients_stage_contacted': 'تم التواصل',
      'clients_stage_proposal': 'عرض مقدم',
      'clients_stage_negotiation': 'تفاوض',
      'clients_stage_won': 'مكتمل',
      'clients_stage_lost': 'مفقود',
      'clients_empty_state': 'لا توجد نتائج لهذا الفلتر حالياً.',
      'clients_load_more': 'تحميل المزيد من العملاء',
      'clients_last_contact': 'آخر تواصل {value}',
      'clients_last_contact_now': 'الآن',
      'clients_last_contact_minutes': 'منذ {minutes} د',
      'clients_last_contact_today': 'اليوم الساعة {time}',
      'clients_last_contact_yesterday': 'أمس الساعة {time}',
      'clients_last_contact_days': 'منذ {days} يوم',
      'clients_last_contact_date': 'في {date}',
      'clients_stage_updated': 'تم تحديث مرحلة العميل',
      'clients_interaction_title': 'تسجيل تفاعل',
      'clients_interaction_type_label': 'نوع التفاعل',
      'clients_interaction_type_call': 'مكالمة',
      'clients_interaction_type_email': 'بريد إلكتروني',
      'clients_interaction_type_meeting': 'اجتماع',
      'clients_interaction_note_hint': 'أضف ملاحظة قصيرة حول نقطة التواصل',
      'clients_interaction_note_error': 'يرجى إضافة ملاحظة قصيرة.',
      'clients_interaction_logged': 'تم تسجيل التفاعل',
      'clients_interaction_save': 'حفظ التفاعل',
      'clients_form_title': 'إضافة عميل جديد',
      'clients_form_name': 'اسم العميل',
      'clients_form_name_error': 'أدخل اسم العميل.',
      'clients_form_company': 'الشركة',
      'clients_form_company_error': 'أدخل اسم الشركة.',
      'clients_form_stage': 'المرحلة',
      'clients_form_value': 'قيمة الصفقة (دولار)',
      'clients_form_email': 'البريد الإلكتروني',
      'clients_form_phone': 'رقم الهاتف',
      'clients_form_tags_hint': 'الوسوم (مفصولة بفاصلة)',
      'clients_form_notes': 'ملاحظات',
      'clients_form_cancel': 'إلغاء',
      'clients_form_save': 'حفظ العميل',
      'clients_form_created': 'تمت إضافة العميل',
      'team': 'الفريق',
      'team_subtitle': 'نسق الأدوار والتركيز والتوفر',
      'team_summary_members': 'الأعضاء',
      'team_summary_active': 'نشطون الآن',
      'team_summary_focus': 'متوسط التركيز',
      'team_summary_checkins': 'متابعات هذا الأسبوع',
      'team_summary_favorites': '{count} مميز',
      'team_summary_overview': '{active} من {total} أعضاء نشطون اليوم',
      'team_search_hint': 'ابحث عن أعضاء الفريق بالاسم أو الدور أو المهارة',
      'team_filter_all': 'الكل',
      'team_status_active': 'نشط',
      'team_status_onboarding': 'قيد الانضمام',
      'team_status_out_of_office': 'خارج المكتب',
      'team_status_contractor': 'متعاقد',
      'team_highlight_title': 'أعضاء مميزون',
      'team_highlight_empty': 'قم بتمييز الأعضاء أو ضبط أهداف التركيز لإبرازهم هنا.',
      'team_highlight_placeholder': 'قم بتمييز الأعضاء أو تحديث حالتهم لعرضهم هنا.',
      'team_add_button': 'إضافة عضو',
      'team_add_title': 'دعوة عضو جديد',
      'team_add_name': 'الاسم الكامل',
      'team_add_name_error': 'أدخل اسم العضو.',
      'team_add_role': 'الدور',
      'team_add_role_error': 'أدخل الدور.',
      'team_add_status': 'الحالة',
      'team_add_email': 'البريد الإلكتروني (اختياري)',
      'team_add_location': 'الموقع (اختياري)',
      'team_add_timezone': 'المنطقة الزمنية (اختياري)',
      'team_add_focus_hours': 'هدف التركيز الأسبوعي (ساعات)',
      'team_add_tasks': 'عدد المهام الأسبوعي',
      'team_add_skills': 'المهارات (مفصولة بفواصل)',
      'team_add_cancel': 'إلغاء',
      'team_add_save': 'إضافة عضو',
      'team_add_success': 'تمت إضافة العضو',
      'team_favorite_added': 'تمت الإضافة إلى المفضلين',
      'team_favorite_removed': 'أزيل من المفضلين',
      'team_status_updated': 'تم تحديث الحالة',
      'team_empty_state': 'لا يوجد أعضاء مطابقون لهذا الفلتر بعد.',
      'team_load_more': 'تحميل المزيد من الأعضاء',
      'team_focus_hours': '{hours}س تركيز',
      'team_tasks_this_week': '{count} مهام هذا الأسبوع',
      'team_member_since': 'انضم في {date}',
      'team_capacity_label': '{percent}% من السعة',
      'team_capacity_average': 'متوسط السعة {percent}%',
      'team_last_active_label': 'آخر نشاط',
      'team_last_active_now': 'الآن',
      'team_last_active_minutes': 'منذ {minutes} د',
      'team_last_active_hours': 'منذ {hours} س',
      'team_last_active_yesterday': 'أمس عند {time}',
      'team_last_active_days': 'منذ {days} يوم',
      'team_last_active_date': 'بتاريخ {date}',
      'team_spotlight_tasks': 'مهام هذا الأسبوع',
      'team_recent_check_in_title': 'أحدث متابعة للفريق',
      'team_recent_check_in_empty': 'سجّل تحديثاً سريعاً لإبراز نشاط الفريق.',
      'team_recent_check_in_cta': 'عرض السجل',
      'team_recent_check_in_log': 'تسجيل متابعة',
      'team_recent_check_in_by': 'تم التسجيل بواسطة {author}',
      'team_recent_check_in_time': 'تم التحديث {time}',
      'team_recent_check_in_sentiment_positive': 'طاقة إيجابية',
      'team_recent_check_in_sentiment_neutral': 'تقدم مستقر',
      'team_recent_check_in_sentiment_attention': 'بحاجة إلى متابعة',
      'team_details_activity_timeline': 'سجل المتابعات',
      'team_details_check_ins_empty': 'لا توجد متابعات بعد. قم بتسجيل التحديث الأول.',
      'team_details_check_in_add': 'تسجيل متابعة',
      'team_details_check_in_sheet_title': 'تسجيل متابعة للفريق',
      'team_details_check_in_summary': 'الملخص',
      'team_details_check_in_summary_hint': 'كيف يسير أداء هذا العضو؟',
      'team_details_check_in_summary_error': 'أضف ملخصاً قصيراً.',
      'team_details_check_in_sentiment': 'التوجه',
      'team_details_sentiment_positive': 'إيجابي',
      'team_details_sentiment_neutral': 'محايد',
      'team_details_sentiment_attention': 'بحاجة لعناية',
      'team_details_check_in_highlights': 'أبرز النقاط (مفصولة بفواصل)',
      'team_details_check_in_next_steps': 'الخطوات التالية (مفصولة بفواصل)',
      'team_details_check_in_cancel': 'إلغاء',
      'team_details_check_in_save': 'حفظ المتابعة',
      'team_details_check_in_success': 'تم حفظ المتابعة',
      'team_details_check_in_highlights_label': 'أبرز النقاط',
      'team_details_check_in_next_label': 'الخطوات التالية',
      'team_details_contact_section': 'معلومات التواصل',
      'team_details_contact_email': 'البريد الإلكتروني',
      'team_details_contact_location': 'الموقع',
      'team_details_contact_timezone': 'المنطقة الزمنية',
      'team_details_skillset': 'مجموعة المهارات',
      'team_details_logged_by': 'تم التسجيل بواسطة {author}',
      'clients_add_button': 'إضافة عميل',
      'clients_log_interaction': 'تسجيل تفاعل',
      'clients_change_stage': 'تغيير المرحلة',
      'clients_view_all': 'عرض الجميع',
      'clients_spotlight_title': 'أهم الصفقات',
      'clients_pipeline_focus': '{count} صفقات ذات تفاعل مرتفع',
      'clients_pipeline_starred': '{count} مميزون',
      'dashboard_clients_card_title': 'علاقات العملاء',
      'dashboard_clients_card_subtitle': '{count} نشط · \${value} في خط الصفقات',
      'tools_clients': 'إدارة العملاء',
      'tools_clients_subtitle': '{count} علاقات نشطة',
      'search_results_clients': 'العملاء',
      'compare': 'مقارنة',
      'search': 'بحث',
      'notifications': 'الإشعارات',
      'notifications_with_count': 'الإشعارات ({count})',
      'notifications_empty': 'لا توجد إشعارات جديدة حالياً!',
      'notifications_mark_all_read': 'تحديد الكل كمقروء',
      'notifications_clear_all': 'مسح جميع الإشعارات',
      'notifications_section_pinned': 'مثبتة',
      'notifications_section_recent': 'أحدث التحديثات',
      'notifications_mark_read': 'تحديد كمقروء',
      'notifications_mark_unread': 'تحديد كغير مقروء',
      'notifications_pin': 'تثبيت في الأعلى',
      'notifications_unpin': 'إلغاء التثبيت',
      'project_linked_tasks': 'المهام المرتبطة',
      'project_progress': 'التقدم {percent}%',
      'mark_completed': 'وضع علامة كمكتمل',
      'mark_active': 'وضع علامة كنشط',
      'add_to_compare': 'إضافة إلى المقارنة',
      'remove_from_compare': 'إزالة من المقارنة',
      'project_no_tasks': 'لا توجد مهام مرتبطة بعد.',
      'settings': 'الإعدادات',
      'theme': 'السمة',
      'language': 'اللغة',
      'dark_mode': 'الوضع الداكن',
      'primary_color': 'اللون الأساسي',
      'ai_placeholder': 'سيتوفر مساعد الذكاء الاصطناعي في إصدار لاحق.',
      'done': 'تم',
      'refreshing': 'جاري تحديث البيانات...',
      'good_morning': 'صباح الخير، {name}',
      'onboarding_title_1': 'نظم عملك بجمال',
      'onboarding_desc_1': 'ابقَ مسيطراً على المشاريع والمهام والموارد في تدفق واحد.',
      'onboarding_title_2': 'تعاون في أجواء هادئة',
      'onboarding_desc_2': 'شارك تقدمك مع الفريق في لوحة ناعمة وبسيطة.',
      'onboarding_title_3': 'خطط بذكاء مع كونيك كيو',
      'onboarding_desc_3': 'تتبع الوقت والمالية والكتالوج بدون عناء.',
      'projects_subtitle': 'مبادراتك الحالية',
      'projects_add_button': 'مشروع جديد',
      'projects_create_title': 'إنشاء مشروع',
      'projects_field_title': 'عنوان المشروع',
      'projects_field_priority': 'الأولوية',
      'projects_field_status': 'الحالة',
      'projects_field_due_date': 'تاريخ الاستحقاق',
      'projects_field_hours': 'الساعات المقدرة',
      'projects_field_progress': 'نسبة التقدم',
      'projects_field_tags': 'الوسوم',
      'projects_tags_hint': 'تسويق، تصميم',
      'projects_create_action': 'حفظ المشروع',
      'projects_validation_title': 'أدخل اسم المشروع أولاً.',
      'projects_validation_hours': 'أدخل تقديراً صحيحاً للساعات.',
      'projects_validation_due': 'اختر تاريخ استحقاق لجدولة المشروع.',
      'projects_due_placeholder': 'اختر تاريخ الاستحقاق',
      'projects_created_success': 'تمت إضافة المشروع إلى مساحة العمل.',
      'project_status_planning': 'تخطيط',
      'project_status_in_progress': 'قيد التنفيذ',
      'project_status_in_review': 'قيد المراجعة',
      'project_status_blocked': 'متوقف',
      'project_status_completed': 'مكتمل',
      'search_projects_hint': 'بحث في المشاريع',
      'filter_all': 'الكل',
      'priority_high': 'عالي',
      'priority_medium': 'متوسط',
      'priority_low': 'منخفض',
      'compare_selected': 'مقارنة ({count})',
      'compare_header': 'مقارنة العناصر',
      'compare_empty': 'اختر حتى ثلاثة عناصر للمقارنة بينها.',
      'clear_compare': 'مسح قائمة المقارنة',
      'compare_type': 'النوع',
      'compare_priority': 'الأولوية',
      'compare_status': 'الحالة',
      'compare_estimate': 'الوقت التقديري',
      'compare_due': 'تاريخ الاستحقاق',
      'payment_summary': 'ملخص المدفوعات',
      'payment_invoices': 'الفواتير',
      'payment_subscriptions': 'الاشتراكات',
      'monthly_tasks': 'مهام الشهر',
      'dashboard_high_priority': 'المشاريع عالية الأولوية',
      'dashboard_today_tasks': 'مهام اليوم',
      'dashboard_focus_hours': 'ساعات التركيز',
      'dashboard_team_pulse_title': 'نبض الفريق',
      'dashboard_team_view_all': 'عرض الفريق',
      'dashboard_team_pulse_active': '{count} نشط اليوم',
      'dashboard_team_pulse_focus': 'متوسط التركيز {hours}س',
      'dashboard_team_pulse_highlight': 'أبرز الأعضاء: {name}',
      'dashboard_team_recent_check_in': 'أحدث متابعة · {name}',
      'dashboard_team_recent_check_in_time': 'تم التسجيل {time}',
      'dashboard_focus_title': 'رؤى التركيز',
      'dashboard_focus_week_label': 'هذا الأسبوع',
      'dashboard_focus_total_label': 'إجمالي الوقت',
      'dashboard_focus_top_task': 'أكثر مهمة تركيزاً · {task}',
      'dashboard_focus_top_task_empty': 'سجل جلسة لكشف المهمة الأكثر تركيزاً.',
      'dashboard_focus_last': 'آخر تركيز {duration} · {time}',
      'dashboard_focus_last_empty': 'لم يتم تسجيل أي جلسات تركيز بعد.',
      'dashboard_insights_card_title': 'صحة مساحة العمل',
      'insights_open_button': 'عرض التحليلات',
      'insights_completion_rate': 'معدل الإنجاز',
      'insights_focus_hours': 'تركيز هذا الأسبوع',
      'insights_net_income': 'صافي الدخل',
      'insights_outstanding_label': 'مستحق {value}',
      'insights_deadline_section': 'المواعيد القادمة',
      'insights_deadline_none': 'لا توجد مواعيد خلال الأيام القليلة القادمة.',
      'insights_deadline_project': 'مشروع',
      'insights_deadline_task': 'مهمة',
      'insights_deadline_due_today': 'يستحق اليوم',
      'insights_deadline_due_tomorrow': 'يستحق غدًا',
      'insights_deadline_due_in': 'يستحق بعد {days} يومًا',
      'insights_weekly_completion': 'منحنى الإنجاز الأسبوعي',
      'insights_weekly_empty': 'لا توجد مهام مجدولة لهذا الأسبوع بعد.',
      'insights_priority_mix': 'توزيع الأولويات',
      'insights_priority_empty': 'لا توجد بيانات للأولويات بعد.',
      'insights_focus_breakdown': 'تفصيل التركيز',
      'insights_focus_empty': 'سجّل جلسات تركيز لعرض التفاصيل هنا.',
      'insights_focus_hours_short': '{hours}س',
      'insights_focus_minutes_short': '{minutes}د',
      'insights_focus_unassigned': 'تركيز غير محدد',
      'insights_recent_sessions': 'جلسات التركيز الأخيرة',
      'insights_sessions_empty': 'سجّل جلسة تركيز لعرض السجل.',
      'insights_title': 'تحليلات مساحة العمل',
      'tasks_add_button': 'مهمة جديدة',
      'tasks_create_title': 'إنشاء مهمة',
      'tasks_field_title': 'عنوان المهمة',
      'tasks_field_category': 'الفئة',
      'tasks_field_description': 'الوصف',
      'tasks_field_priority': 'الأولوية',
      'tasks_field_status': 'الحالة',
      'tasks_field_due_date': 'تاريخ الاستحقاق',
      'tasks_field_hours': 'الساعات المقدرة',
      'tasks_create_action': 'حفظ المهمة',
      'tasks_validation_due': 'اختر تاريخ استحقاق لجدولة المهمة.',
      'tasks_due_placeholder': 'اختر تاريخ الاستحقاق',
      'tasks_created_success': 'تمت إضافة المهمة إلى قائمتك.',
      'tasks_today': 'اليوم',
      'tasks_calendar': 'التقويم',
      'tasks_total': 'إجمالي المهام',
      'tasks_average': 'متوسط يومي',
      'tasks_hours': 'إجمالي الساعات',
      'search_tasks_hint': 'بحث في المهام',
      'scheduler_title': 'جدول المواعيد',
      'scheduler_subtitle': 'رتب يومك بمساحات تركيز ذات طابع.',
      'scheduler_add_block': 'إضافة كتلة',
      'scheduler_new_block': 'كتلة مجدولة جديدة',
      'scheduler_title_field': 'العنوان',
      'scheduler_description_field': 'الوصف',
      'scheduler_pick_time': 'اختر وقت البدء',
      'scheduler_duration_option': '{minutes} دقيقة',
      'scheduler_save': 'حفظ الكتلة',
      'scheduler_validation_title': 'أدخل عنواناً للكتلة أولاً.',
      'scheduler_created_success': 'تمت إضافة الكتلة إلى يومك.',
      'scheduler_empty': 'لا توجد جلسات مخططة. أضف كتلة التركيز التالية.',
      'scheduler_removed': 'تم حذف الكتلة من الجدول.',
      'scheduler_tag_focus': 'تركيز',
      'scheduler_tag_team': 'فريق',
      'scheduler_tag_client': 'عميل',
      'scheduler_tag_deep_work': 'عمل عميق',
      'task_details_schedule': 'الجدول',
      'task_due_date': 'تاريخ الاستحقاق {date}',
      'task_details_description': 'الوصف',
      'task_details_hours': 'الساعات المقدرة',
      'task_details_mark_done': 'وضع علامة كمكتمل',
      'task_details_mark_active': 'وضع علامة كنشط',
      'task_details_marked_done': 'تم وضع علامة على المهمة كمكتملة',
      'task_details_marked_active': 'تمت إعادة المهمة كفعّالة',
      'task_overlay_front': 'معاينة للمهمة، اضغط للانقلاب ورؤية التفاصيل.',
      'filter_status': 'الحالة',
      'status_in_progress': 'قيد التنفيذ',
      'status_upcoming': 'قادمة',
      'status_done': 'منتهية',
      'load_more': 'تحميل المزيد',
      'catalog_search_hint': 'بحث في الكتالوج',
      'type_template': 'قالب',
      'type_document': 'مستند',
      'type_task': 'مهمة',
      'view_list': 'قائمة',
      'view_grid': 'شبكة',
      'catalog_add_to_compare': 'أضف إلى المقارنة',
      'catalog_remove_from_compare': 'إزالة من المقارنة',
      'catalog_open_compare': 'افتح لوحة المقارنة',
      'catalog_estimated_hours': '{hours} ساعة تقديرية',
      'catalog_highlights_title': 'أبرز نقاط المقارنة',
      'catalog_highlight_priority': 'الأولوية • {priority}',
      'catalog_highlight_type': 'الفئة • {type}',
      'catalog_highlight_tags': 'الوسوم • {tags}',
      'catalog_highlight_hours': 'الجهد • {hours} ساعة',
      'catalog_flip_hint': 'انقر على البطاقة لقلبها واستكشاف المزيد من التفاصيل.',
      'catalog_flip_button_front': 'عرض النقاط البارزة',
      'catalog_flip_button_back': 'العودة إلى التفاصيل',
      'catalog_compare_snackbar_added': 'تمت الإضافة إلى المقارنة',
      'catalog_compare_snackbar_removed': 'تمت الإزالة من المقارنة',
      'compare_selected_full': 'مقارنة العناصر المختارة ({count})',
      'language_en': 'الإنجليزية',
      'language_ar': 'العربية',
      'settings_goals_subtitle': 'حدّث الأهداف الظاهرة في لوحة التحكم',
      'primary_color': 'اللون الأساسي',
      'templates_title': 'القوالب',
      'templates_subtitle': 'وفر الوقت مع اللبنات الجاهزة.',
      'templates_search_hint': 'بحث في القوالب',
      'templates_hours': '{hours} ساعة تقديرية',
      'templates_added_to_catalog': 'تمت إضافة القالب إلى الكتالوج.',
      'templates_add_to_catalog': 'إضافة إلى الكتالوج',
      'templates_popular': 'شائع',
      'library_title': 'مكتبتي',
      'library_subtitle': 'مستندات وعروض وملاحظات في لمحة.',
      'library_search_hint': 'بحث في المكتبة',
      'library_link_copied': 'تم نسخ الرابط للمشاركة السريعة.',
      'time_tracker_title': 'متعقب الوقت',
      'time_tracker_subtitle': 'سجل جلسات التركيز بأناقة باستيل.',
      'time_tracker_task_label': 'المهمة المرتبطة',
      'time_tracker_no_task': 'جلسة غير مرتبطة',
      'time_tracker_last_session': 'آخر جلسة',
      'time_tracker_last_session_time': 'تم التسجيل في {time}',
      'time_tracker_last_session_empty': 'لم يتم تسجيل أي جلسات بعد.',
      'time_tracker_reset': 'إعادة ضبط',
      'time_tracker_start': 'بدء',
      'time_tracker_pause': 'إيقاف مؤقت',
      'time_tracker_stop': 'إيقاف',
      'time_tracker_logged': 'تم تسجيل الجلسة بنجاح.',
      'time_tracker_summary_title': 'ملخص التركيز',
      'time_tracker_weekly_total': '{duration} مسجلة هذا الأسبوع',
      'time_tracker_total': '{duration} مسجلة إجمالاً',
      'time_tracker_top_task': 'أكثر مهمة تركيزاً · {task}',
      'time_tracker_top_task_empty': 'سجل جلسة لإظهار المهمة الأكثر تركيزاً.',
      'time_tracker_history': 'سجل الجلسات',
      'time_tracker_history_empty': 'لا توجد جلسات تركيز بعد. ابدأ واحدة لبناء الزخم.',
      'time_tracker_clear_history': 'مسح السجل',
      'time_tracker_session_at': 'تم التسجيل في {time}',
      'time_tracker_history_cleared': 'تم مسح سجل الجلسات.',
      'dark_mode': 'الوضع الداكن',
      'profile_trial': 'تنتهي الفترة التجريبية بعد {days} يومًا',
      'invalid_email': 'يرجى إدخال بريد إلكتروني صحيح',
      'required_field': 'هذا الحقل مطلوب',
      'password_too_short': 'يجب أن لا تقل كلمة المرور عن 6 أحرف',
      'password_mismatch': 'كلمتا المرور غير متطابقتين',
      'email_address': 'البريد الإلكتروني',
      'full_name': 'الاسم الكامل',
      'confirm_password': 'تأكيد كلمة المرور',
      'password_strength': 'قوة كلمة المرور',
      'search_global_hint': 'ابحث عن أي شيء',
      'search_results_projects': 'المشاريع',
      'search_results_tasks': 'المهام',
      'search_results_catalog': 'الكتالوج',
      'search_results_templates': 'القوالب',
      'search_results_team': 'الفريق',
      'search_history': 'عمليات البحث الأخيرة',
      'search_clear_history': 'مسح السجل',
      'search_empty_history': 'ابدأ الاستكشاف لإنشاء سجل لعمليات البحث.',
      'drawer_trial': 'تجريبي',
      'settings_profile': 'تفاصيل الحساب',
      'settings_subscription': 'خطة الاشتراك',
      'settings_brand': 'عناصر الهوية',
      'settings_bank': 'الحساب البنكي',
      'ai_future_title': 'قريباً',
      'ai_future_message': 'سيتوفر مساعد الذكاء الاصطناعي في إصدار لاحق.'
    }
  };

  String translate(String key, {Map<String, String>? params}) {
    var value = _localizedValues[locale.languageCode]?[key] ?? key;
    if (params != null) {
      params.forEach((placeholder, replacement) {
        value = value.replaceAll('{$placeholder}', replacement);
      });
    }
    return value;
  }

  TextDirection get textDirection => locale.languageCode == 'ar' ? TextDirection.rtl : TextDirection.ltr;

  static AppLocalizations of(BuildContext context) => Localizations.of<AppLocalizations>(context, AppLocalizations)!;
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => AppLocalizations.supportedLocales.any((l) => l.languageCode == locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async => AppLocalizations(locale);

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}
